### ISSUE TITLE
Remote Peer not able to establish a connection: peerjs-python

### ISSUE THREAD

**Issue by njcurtis3** [ambianic/ambianic-ui#395]
Mostly the same issue here @Luca Capra. I've noticed after a day (or less), the UI (or peer connection) will not connect, therefore the UI will not connect to the edge device and not show an updated timeline

Command Line Output:
`ambianic-edge    | 2020-06-04 14:47:00 WARNING /usr/local/lib/python3.7/dist-packages/peerjs/ext/http-proxy.py.peer_error(129): peerConnectionStatus None`
[ambianic-log.txt](https://github.com/ambianic/ambianic-ui/files/4730986/ambianic-log.txt)

**Comment by ivelin** [comment]
The log file you attached shows a different problem. It looks like the rtsp input source is not generating samples. Either gstreamer got jammed or the camera is not responding.
I've seen this with my cameras happen occasionally. It turns out that there are many flavors of RTSP and gstreamer is not completely robust to handling all of these without jamming.

Try the HTTP URI for camera sources instead of rtsp. See if that helps with this particular issue.

The WebRTC connectivity with discussed is still a valid problem, but it's not the one I see in the logs you attached.

**Comment by njcurtis3** [comment]
Here is docker-compose logs. Not gettign the same errors, but the timeline is not updating in the UI.

[docker-compose logs.txt](https://github.com/ambianic/ambianic-ui/files/4731573/docker-compose.logs.txt)

**Comment by ivelin** [comment]
This issue is probably solved by now. I have not observed or heard of it for some time. Needs verification and test coverage before closing.
