### ISSUE TITLE
Implement live view of camera stream

### ISSUE THREAD

**Issue by mchapman67** [ambianic/ambianic-ui#498]
**Is your feature request related to a problem? Please describe.**
It would be very beneficial to implement a live view of the camera during the initial on boarding of the Ambianic box to help make adjustments to the camera so that the detection zone of the camera can be optimized, ie., make sure the camera field-of-view isn’t obstructed by furniture, etc,.

**Describe the solution you'd like**
I would like to see a live view of the camera appear during the initial onboarding for the Ambianic box via the WiFi Captive portal. Once the installer is satisfied the camera is installed properly, the page can be dismissed. 

***Live Preview Display Requirements***

- [ ] Goal of 1fps refresh rate
- [ ] Latest idle source cam snapshot or latest detection within the past 1 second
- [ ] Debug information with detection details: confidence score, bounding box, pose keypoints, body vectors, etc.
- [ ] Display actual fps
- [ ] Show real time and date in user locale

**Comment by ivelin** [comment]
This came up today while helping a remote use install an ambianic box. It would have saved a substantial amount of time if it was possible to see real time what the camera sees and detects. Instead the user and I had to guess semi-blindly based on a few person detections in the timeline. Calibrating the camera position for fall detections takes even longer without ability for a live preview.

**Comment by ivelin** [comment]
related to https://github.com/ambianic/ambianic-edge/issues/340

**Comment by ivelin** [comment]
There was[ another installation discussion today](https://ambianicai.slack.com/archives/C012L70UTMG/p1615142396004400) with a new user, who was struggling to configure the camera angle in a way that it can detect people in the hallway in front of his front door. Having a live preview and detection debugging mode could have save time.

**Comment by mchapman67** [comment]
Yes, it looks like the issue is gaining traction.

**Comment by ivelin** [comment]
Follow up thoughts on this topic. Two potential implementation design alternatives:

1. Use live WebRTC video channel from ambianic edge to PWA. This route requires transforming video frames from a pipeline source to a webrtc codec and wire protocol. Bandwidth requirements around 1-2Mbps. CPU+GPU requirements medium-high if we use GPU accelerated h264 as coded. However since the GPU is also occupied by picam or rtsp decoding, more than likely the CPU+GPU load will be high. Since the current CPU is already high due to the constant AI inferencing on incoming frames, there is likely to be a conflict and visible delays and/or misalignments in the live feed between image capture and detections. Another issue here is the fact that CPU may be too busy to provide enough priority to either the live stream or AI inferencing to do their expected job at 1fps minimum.

2. Use datachannel over WebRTC to push thumbnail snapshots of images that come at the end of each pipeline run. This approach will result in lower res (200x300) and low frame rate (~1fps) refresh of the live preview in the PWA, however it will have significant performance advantages. Bandwidth will be in the order of 30Kbps vs 1-2Mbps. CPU and GPU add-on load will be very low, because we can reuse the images and inference/detection annotations provided at the end of each a pipeline run. We would just need to keep updating two files: latest-snapshot.jpg and latest-detection.json. Both files are essentially copies of data already processed and saved by store.py. PWA can continuously poll for these two files via the existing peerFetch() API with a target such as `http://edge-host/preview/latest-snapshot.jpg`. The PWA can also reuse the existing components for rendering an image and detection annotations that are currently used in the timeline view.

Overall approach 1 is HD but high CPU+GPU load and sync issues for detection annotations. While 2 is lower resolution and fps but also low CPU+GPU load and precise detection annotations.

**Comment by vickywane** [comment]
@ivelin It seems this issue is being suspended till the Notifications feature is complete.

**Comment by ivelin** [comment]
@vickywane 's UX mockup proposal:

https://www.figma.com/file/pF8Cc73vBZRHwAPRM8HK28/ambianic-installation-live-view?node-id=0%3A1

**Comment by ivelin** [comment]
Related backend issue: https://github.com/ambianic/ambianic-edge/issues/340
